/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemQrIdRouteImport } from './routes/item-qr.$id'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppRequisitionsRouteImport } from './routes/_app/requisitions'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCoaFormsRouteImport } from './routes/_app/coa-forms'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAssistantRouteImport } from './routes/_app/assistant'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemQrIdRoute = ItemQrIdRouteImport.update({
  id: '/item-qr/$id',
  path: '/item-qr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppRequisitionsRoute = AppRequisitionsRouteImport.update({
  id: '/requisitions',
  path: '/requisitions',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoaFormsRoute = AppCoaFormsRouteImport.update({
  id: '/coa-forms',
  path: '/coa-forms',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/assistant': typeof AppAssistantRoute
  '/audit': typeof AppAuditRoute
  '/categories': typeof AppCategoriesRoute
  '/coa-forms': typeof AppCoaFormsRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/requisitions': typeof AppRequisitionsRoute
  '/scan': typeof AppScanRoute
  '/stock': typeof AppStockRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/item-qr/$id': typeof ItemQrIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/assistant': typeof AppAssistantRoute
  '/audit': typeof AppAuditRoute
  '/categories': typeof AppCategoriesRoute
  '/coa-forms': typeof AppCoaFormsRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/requisitions': typeof AppRequisitionsRoute
  '/scan': typeof AppScanRoute
  '/stock': typeof AppStockRoute
  '/suppliers': typeof AppSuppliersRoute
  '/users': typeof AppUsersRoute
  '/item-qr/$id': typeof ItemQrIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/coa-forms': typeof AppCoaFormsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/requisitions': typeof AppRequisitionsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/users': typeof AppUsersRoute
  '/item-qr/$id': typeof ItemQrIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/assistant'
    | '/audit'
    | '/categories'
    | '/coa-forms'
    | '/dashboard'
    | '/inventory'
    | '/requisitions'
    | '/scan'
    | '/stock'
    | '/suppliers'
    | '/users'
    | '/item-qr/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/assistant'
    | '/audit'
    | '/categories'
    | '/coa-forms'
    | '/dashboard'
    | '/inventory'
    | '/requisitions'
    | '/scan'
    | '/stock'
    | '/suppliers'
    | '/users'
    | '/item-qr/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/assistant'
    | '/_app/audit'
    | '/_app/categories'
    | '/_app/coa-forms'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/requisitions'
    | '/_app/scan'
    | '/_app/stock'
    | '/_app/suppliers'
    | '/_app/users'
    | '/item-qr/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ItemQrIdRoute: typeof ItemQrIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item-qr/$id': {
      id: '/item-qr/$id'
      path: '/item-qr/$id'
      fullPath: '/item-qr/$id'
      preLoaderRoute: typeof ItemQrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requisitions': {
      id: '/_app/requisitions'
      path: '/requisitions'
      fullPath: '/requisitions'
      preLoaderRoute: typeof AppRequisitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coa-forms': {
      id: '/_app/coa-forms'
      path: '/coa-forms'
      fullPath: '/coa-forms'
      preLoaderRoute: typeof AppCoaFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCoaFormsRoute: typeof AppCoaFormsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppRequisitionsRoute: typeof AppRequisitionsRoute
  AppScanRoute: typeof AppScanRoute
  AppStockRoute: typeof AppStockRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppAuditRoute: AppAuditRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCoaFormsRoute: AppCoaFormsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppRequisitionsRoute: AppRequisitionsRoute,
  AppScanRoute: AppScanRoute,
  AppStockRoute: AppStockRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ItemQrIdRoute: ItemQrIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
